INSERT INTO TUSERS (ID,NIF,CODIGOMESA,PASSWORD,EMAIL,NAME)VALUES(51,'45443827R',1,'fcW3i1ciT8','jorge@gmail.com','Jorge');
INSERT INTO TUSERS (ID,NIF,CODIGOMESA,PASSWORD,EMAIL,NAME) VALUES(56,'54313432L',1,'3WwJXICTdi','sara@gmail.com','Sara');
INSERT INTO TUSERS (ID,NIF,CODIGOMESA,PASSWORD,EMAIL,NAME) VALUES(60,'34587263E',4,'jPzUf9mRlI','saul@gmail.com','Saul');
INSERT INTO TUSERS (ID,NIF,CODIGOMESA,PASSWORD,EMAIL,NAME) VALUES(53,'75443827R',3,'f6FVZov56c','Rober@gmail.com','Roberto');
INSERT INTO TOPCIONES VALUES('IU');
INSERT INTO TOPCIONES VALUES('PCPE');
INSERT INTO TOPCIONES VALUES('PP');
INSERT INTO TOPCIONES VALUES('PSOE');
INSERT INTO TOPCIONES VALUES('Podemos');
INSERT INTO TPLACES VALUES(1,'Mi colegio','pas1','oviedo','espana');
INSERT INTO TPLACES VALUES(2,'Tu colegio','pas2','gijon','espana');
INSERT INTO TPLACES VALUES(3,'Su colegio','pas3','langreo','espana');
INSERT INTO TPLACES VALUES(4,'Nuestro','pas4','aviles','espana');
INSERT INTO TVOTANTES VALUES('34587263E')
INSERT INTO TCONFIG (FECHA,HORAINICIO,HORAFIN)VALUES(CURRENT_DATE(),1,23);